### ISSUE TITLE
unable to use

### ISSUE THREAD

**Issue by dasp24** [w11k/angular-sticky-things#47] opened 2019-10-23 16:21 UTC
This is the error I'm getting:

ERROR in node_modules/@w11k/angular-sticky-things/lib/sticky-thing.directive.d.ts(58,53): error TS2304: Cannot find name 'DOMRect'.

**Comment by tobiasatw11k** [comment] 2019-10-24 18:57
@dasp24 please try using the current latest version 1.1.8. if the error still occurs, please provide more information. which angular, typescript version are you using? what does your tsconfig.json look like?

**Comment by tobiasatw11k** [comment] 2019-10-24 21:48
duplicate of #34

**Closed by tobiasatw11k** 2019-10-24 21:48 UTC
