### ISSUE TITLE
Wrong size calculation with `marginTop`

### ISSUE THREAD

**Issue by csimpi** [w11k/angular-sticky-things#40] opened 2019-07-03 06:36 UTC
Hi,
something is wrong with the spacer's size calculation method when I use `marginTop` attribute.
It handles the margin's value as a string and the height + margin values are concatenated as strings like: 5080px. The spacer covers my whole screen.

**Comment by JohannesW11K** [comment] 2019-09-23 14:12
Duplicate of #23 . Fix coming with the next release!

**Closed by JohannesW11K** 2019-09-23 14:12 UTC
